#!/usr/bin/env bash
# Description: Generate and set a random hostname on Linux
# Requires: sed, awk
# Usage: set-random-hostname

# names-generator is a go script copied and modified from https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go
# I changed it to be a standalone script using `package main` and added a `func main()` to it.

__set_random_hostname() {
  local new_hostname=$(names-generator)
  # set new hostname
  hostnamectl set-hostname "$new_hostname"
  # set new hostname in /etc/hosts
  sed -i "2 s/^.*$/127.0.1.1       $new_hostname/g" /etc/hosts
}

__set_random_hostname
